# TUTORIAL: https://github.com/pages-themes/hacker?tab=readme-ov-file#usage

# theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Kelly Chen's Personal Site
description: Hello! You're probably here because you want to know more about me.

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
